### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by lukeeexd** [sladkoff/minecraft-prometheus-exporter#20]
Getting this after I install https://i.imgur.com/BtYPUPj.png I added 

`  - job_name: 'minecraft'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9225']`

to /etc/prometheus/prometheus.yml and restarted prometheus but still nothing

`tcp6       0      0 127.0.0.1:9225          :::*                    LISTEN      9898/java`

Edit: Updated to latest vesion on github and I get this now https://i.imgur.com/v19SwwK.png

Edit2: Guess you can ignore all this. I installed grafana and it filled all the dashboards. only thing is seems the TPS reading is way off?

**Comment by sladkoff** [comment]
1. The `404 not found` was probably just because you didn't request the correct URL which should have been `/metrics`. Prometheus scrapes this path by default.

2. If you upgraded to [v1.3.0](https://github.com/sladkoff/minecraft-prometheus-exporter/releases/tag/v1.3.0) of the plugin and have the default `host` option set, then you were probably trying to access the exporter server from a different host (not localhost). If your Prometheus is running on that same host, all is fine.

3. How is that? Too high? Too low? How did you test? This will heavily depend on your Prometheus scrape configuration. Say your `scrape_interval` is set to 1 minute (I believe that's the default) - all your metrics will be accurate to one minute. In other words a short lag spike won't be visible if it happens in between the scrapes.

**Comment by lukeeexd** [comment]
I tried metrics too and was same error. Yeah default is localhost, everything is on same machine. Guess it doesn’t matter once grafana is populated.

Yeah I realised after you can change the display time in grafana it was set to 30mins I changed to 1min. I’ll have a look at the configs later

**Comment by lukeeexd** [comment]
Is there a way to get the players graph to only show players online and not total players?

**Comment by sladkoff** [comment]
Try `mc_players_total{state="online"}`
