### ISSUE TITLE
TPS metric is inaccurate

### ISSUE THREAD

**Issue by gp-Airee** [sladkoff/minecraft-prometheus-exporter#23]
I understand this plugin isn't officially supported on 1.8, but the metric always reads 20. It'd be nice if it worked on 1.8 too!

**Comment by Spacey** [comment]
I also have this issue on the latest version of Paper 1.14.4, it only seems to send the correct TPS every now and again.

**Comment by BirkhoffLee** [comment]
Same here, always reads 20.

**Comment by sladkoff** [comment]
What are you guys comparing the TPS to?

As far as I remember I re-used code from [LagMeter](https://www.spigotmc.org/resources/lagmeter.19396/) while it was still open source and on GitHub. I was testing the TPS metric against the LagMeter `/tps` command.

I will keep this open and look into it when I get the time.

**Comment by BirkhoffLee** [comment]
After testing it does drop to like 14 or something, but it’s mostly inaccurate comparing to what I see in the output of in-game `/tps`. I also use [React](https://www.spigotmc.org/resources/react-smart-server-performance-1-14-update.21057/) to monitor server stats in-game, and the TPS stat from that just differs a lot from this plugin.

**Comment by phemmer** [comment]
Was also seeing unexpected values out of this measurement, and took a look at the code. The issue is how TPS is being calculated. On [TpsCollector.java#32](https://github.com/sladkoff/minecraft-prometheus-exporter/blob/ee958d513e227dd5aac123a5f6e9616c77fbc659/src/main/java/de/sldk/mc/tps/TpsCollector.java#L32) we have:

    long timeSpent = (now - this.lastPoll) / 1000;

What this is doing is taking the amount of wall clock time between now and 40 ticks ago, measured in milliseconds, and then truncating it down to seconds.
So lets say we've got a TPS of 15. Then 40 ticks would take 2,667ms. The code takes that and divides by 1000, so it becomes 2.667. Then it converts that to a `long`, and it becomes 2. Just 2. So now the code thinks that the last 40 ticks took 2 seconds, instead of 2.667 seconds. It then divides the expected number of ticks (40) by that value (2) and gets a TPS of 20, instead of 15.

For this to show something other than 20, the TPS has to drop to such a low rate that the truncation produces a different value. In practice, this means the TPS has to drop down to about 13.

**Comment by gp-Airee** [comment]
Just shade in https://github.com/lucko/spark/tree/master/spark-common for a TPS metric.

**Comment by sladkoff** [comment]
Due to popular demand this is now a bug.

@phemmer @gp-Airee PRs are always welcome, you guys already did half the job :smile: 
The current implementation isn't set in stone at all and you can feel free to replace it completely.

**Comment by phemmer** [comment]
I know barely anything about java, so I'm probably not the best person to tackle this. However my first thoughts are to either change the type from `long` to `double`, or keep the unit as milliseconds (don't divide by 1000), and multiply by 1000 on line 35.

IMHO, using a decimal data type is overkill (assuming that `BigDecimal` is the same as decimal data types in other languages). Decimal is heavy, and we don't need that level of precision.
