### ISSUE TITLE
Using multiple instances of Prometheus Exporter on different Dashboards

### ISSUE THREAD

**Issue by OfficialTehlo** [sladkoff/minecraft-prometheus-exporter#25]
Hi! 

First of all, love the fact that this panel and this plugin exists because I love to view my Server Stats on a webpanel.

However, I would like to use Multiple MC servers to be displayed on their own Dashboard instead of combined in 1 Dashboard (if possible)
With using the Labels my prometheus.yml doesn't even save, just gives me errors that it can't load the config and with using 2 servers I get:

N/A for Players Online
N/A for JVM Memory
N/A for TPS

Any way to fix this?
Thanks in advance!

**Comment by sladkoff** [comment]
Prometheus/Grafana configuration isn't in the scope of this issue tracker - please refer to the [Prometheus Docs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/) + [Grafana Docs](https://grafana.com/docs/grafana/latest/features/datasources/prometheus/).

This issue is quite old by now (sorry). If you still need help, please create a [gist](https://gist.github.com/) of your dashboard JSON and I can take a look and maybe give you a hint.
