### ISSUE TITLE
Worlds filter

### ISSUE THREAD

**Issue by SlimeDog** [sladkoff/minecraft-prometheus-exporter#8]
Can the universe of worlds reported be filtered? Many of my worlds are uninteresting, in terms of entities and chunks loaded.

**Comment by sladkoff** [comment]
Yes, you can filter by worlds. It's not a feature related to the plugin though.

You're just telling Grafana to query the Prometheus database. Please refer to the Prometheus [Querying Basics](https://prometheus.io/docs/querying/basics/) to learn how to write advanced queries and more.

#### Simple example

If you're still using the exemplary dashboard provided in this repo, go and edit the "Loaded Chunks" panel.

The default query is `mc_loaded_chunks_total`. 
You could change that to `mc_loaded_chunks_total{world='YOUR_WORLD_NAME_HERE'}` 

Instead of showing all chunks per world, you'd see only the chunks for the specified world now. 

Grafana also supports [Templating](http://docs.grafana.org/reference/templating/) so that you could have dynamic filters, but that's more advanced.

#### Note 
Filtering and visualizing the stats is beyond the responsibility of this plugin. The plugin only **exports** the raw data to Prometheus which can then be **queried** in order to get enhanced views of the data.

**Comment by SlimeDog** [comment]
Yes, of course. I found what I wanted. Appreciate the guidance.
