### ISSUE TITLE
future-request: Add CPU load and multiple server support

### ISSUE THREAD

**Issue by BirkhoffLee** [sladkoff/minecraft-prometheus-exporter#9]
As the title says. They would be very helpful too.
Thanks for the hard work!

**Comment by sladkoff** [comment]
#### CPU load
Unfortunately it's not very straight-forward to read the respective CPU usage from within a Java process.
You're much better of using another Prometheus exporter designed specifically for reporting hardware stats on your machine. 

You'll have to see what works best for you but I'd recommend [Node exporter](https://github.com/prometheus/node_exporter) and [cadvisor](https://github.com/google/cadvisor). 

Node exporter is simpler and works great if you want to monitor the CPU load of the entire system. 
If you happen to be running your MC server in a container (e.g. docker), then cadvisor may be better since it can report CPU usage on a per-container-basis as far as I know. 

#### Multiple server support
I'll look into it.

**Comment by sladkoff** [comment]
Better later than never, I guess... I added instructions for how to set up a scrape config for multiple servers.
